{"name": "test_get_access_code[错误的accesstoken返回失败]", "status": "passed", "parameters": [{"name": "token", "value": "'wrong'"}, {"name": "result", "value": "False"}], "start": 1580868311662, "stop": 1580868311779, "uuid": "89fd9119-b1bd-421e-b7b7-b05570327ac8", "historyId": "a807f9ff23820a19726a54ff50a9c97a", "fullName": "TestCase.TestGetAccessCode.test_GetAccessCode.Test_GetAccessCode#test_get_access_code[错误的accesstoken返回失败]", "labels": [{"name": "story", "value": "获取code"}, {"name": "feature", "value": "Test_GetAccessCode接口"}, {"name": "parentSuite", "value": "TestCase.TestGetAccessCode"}, {"name": "suite", "value": "test_GetAccessCode"}, {"name": "subSuite", "value": "Test_GetAccessCode"}, {"name": "host", "value": "HTBC-20140822KE"}, {"name": "thread", "value": "18080-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.TestGetAccessCode.test_GetAccessCode"}], "links": [{"type": "issue", "url": "case id：020402", "name": "case id：020402"}]}